version: 2.1

orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:20.12"
    steps:
      - node/install:
          node-version: '20.12'         
      - checkout
      - run:
          name: Install Root Dependencies
          command: |
            npm install
            echo "Root dependencies installed."
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run install-client
      - run:
          name: Install Server Dependencies
          command: |
            cd server && npm install
            echo "Server dependencies installed."
      - run:
          name: Lint
          command: |
            npm run lint 
      - run:
          name: Front-End Build
          command: |
            npm run build-client
            echo "Frontend built successfully."
      - run:
          name: Server Build
          command: |
            npm run build-server
            echo "Backend built successfully."

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '20.12' 
      - checkout
      - aws-cli/setup
      - run:
          name: Set Up AWS Credentials
          command: |
            echo "Setting up AWS credentials..."
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            curl -Lo awsebcli.zip https://github.com/aws/aws-elastic-beanstalk-cli-setup/archive/v1.0.zip
            unzip awsebcli.zip
            ./aws-elastic-beanstalk-cli-setup-1.0/scripts/bundled_installer
      - run:
          name: Initialize Elastic Beanstalk CLI
          command: |
            cd server
            eb init -p node.js -r $AWS_DEFAULT_REGION Employee-polling-app-env
      - run:
          name: Deploy Frontend to S3
          command: |
            echo "Deploying Frontend to S3..."
            aws s3 sync frontend/build s3://$BUCKET_NAME --delete
      - run:
          name: Deploy Backend to Elastic Beanstalk
          command: |
            echo "Deploying Backend to Elastic Beanstalk..."
            eb deploy $BEANSTALK_INSTANCE
            echo "Deployment completed."

workflows:
  employee-polling:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - hold
